services:

  api:
    image: scmosoeu/fresh_produce:1.0
    container_name: fresh_produce_api
    restart: always
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  
  redis:
    image: redis:7.2.5-alpine
    container_name: redisdb
    restart: always
    ports:
      - 6397:6397

  postgres:
    image: postgres:12.19
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8001:8001
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres

  neo4j:
    image: neo4j:5.21.2
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687