services:

  api:
    image: scmosoeu/fresh_produce:1.0
    container_name: fresh_produce_api
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  
  redis:
    image: redis:7.2.5-alpine
    container_name: redisdb
    ports:
      - 6397:6397