services:

  api:
    image: scmosoeu/fresh_produce:1.0
    container_name: fresh_produce_api

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672